# Generated by Django 5.1.4 on 2024-12-19 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Executor',
        ),
    ]
