# Generated by Django 5.1.4 on 2024-12-19 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0002_delete_customer_delete_executor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='executorprofile',
            name='skills',
            field=models.CharField(blank=True, help_text='List of skills', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='executorprofile',
            name='categories',
            field=models.ManyToManyField(related_name='categories_profile', to='MySite.category'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_words', models.CharField(help_text='specialization', max_length=50)),
                ('title', models.CharField(help_text='Name of the task', max_length=100)),
                ('description', models.TextField(help_text='Description of your task')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price', max_digits=10)),
                ('deadline', models.DateTimeField(help_text='Your deadline')),
                ('categories', models.ManyToManyField(related_name='categories', to='MySite.category')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='chat',
            name='task',
            field=models.ForeignKey(help_text='Chat for this task', on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='MySite.task'),
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
