# Generated by Django 5.1.4 on 2024-12-21 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0003_category_customerprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutorPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(blank=True, help_text='List of skills', max_length=100, null=True)),
                ('experience', models.TextField(blank=True, help_text='Description of experience or info about you')),
                ('portfolio', models.TextField(blank=True, help_text='Portfolio or projects links')),
                ('rating', models.FloatField(default=0, help_text='Average rating')),
                ('categories', models.ManyToManyField(related_name='categories_profile', to='MySite.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='executor_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
        migrations.AlterField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(default='Not have categories', related_name='categories', to='MySite.category'),
        ),
        migrations.DeleteModel(
            name='ExecutorProfile',
        ),
    ]
