# Generated by Django 5.1.4 on 2024-12-23 22:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0004_customerportfolio_executorportfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Created time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is it task done?'),
        ),
        migrations.AlterField(
            model_name='executorportfolio',
            name='categories',
            field=models.ManyToManyField(related_name='categories_sk', to='MySite.category'),
        ),
    ]
