# Generated by Django 5.1.4 on 2024-12-24 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0007_remove_task_is_active_task_executor_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='type your text', max_length=200)),
                ('offer', models.IntegerField(default=0, help_text='Your proposal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='MySite.task')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('task', 'executor'), name='unique_task_executor_comment')],
            },
        ),
    ]
