# Generated by Django 5.1.4 on 2024-12-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0009_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the chat open?'),
        ),
    ]
