# Generated by Django 5.1.4 on 2024-12-28 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0010_alter_chat_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='task',
            field=models.ForeignKey(help_text='Chat for this task', on_delete=django.db.models.deletion.CASCADE, related_name='task_chats', to='MySite.task'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(help_text='type your text', max_length=200),
        ),
    ]
